language: php
php:
  - '7.4'
  - '8.0'
install:
  - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar
  - wget -O local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64
  - chmod +x local-php-security-checker
script:
  - php php-cs-fixer-v2.phar fix --rules @PSR1,@PSR2,no_whitespace_in_blank_line --dry-run --diff .
  - ./local-php-security-checker
